.TH "b2sum" 1 "GNU coreutils 8.28" "User Commands"
.SH NAME
b2sum \- a GNU coreutils 8.28 program
.SH DESCRIPTION
.B OOOPS!
Due to the lack of perl on the build system, we were
unable to create a proper manual page for
.B b2sum.
For concise option descriptions, run
.IP
.B env b2sum --help
.PP
The full documentation for
.B b2sum
is maintained as a Texinfo manual, which should be accessible
on your system via the command
.IP
.B info \(aq(coreutils) b2sum invocation\(aq
