.TH "base32" 1 "GNU coreutils 8.28" "User Commands"
.SH NAME
base32 \- a GNU coreutils 8.28 program
.SH DESCRIPTION
.B OOOPS!
Due to the lack of perl on the build system, we were
unable to create a proper manual page for
.B base32.
For concise option descriptions, run
.IP
.B env base32 --help
.PP
The full documentation for
.B base32
is maintained as a Texinfo manual, which should be accessible
on your system via the command
.IP
.B info \(aq(coreutils) base32 invocation\(aq
