.TH "base64" 1 "GNU coreutils 8.28" "User Commands"
.SH NAME
base64 \- a GNU coreutils 8.28 program
.SH DESCRIPTION
.B OOOPS!
Due to the lack of perl on the build system, we were
unable to create a proper manual page for
.B base64.
For concise option descriptions, run
.IP
.B env base64 --help
.PP
The full documentation for
.B base64
is maintained as a Texinfo manual, which should be accessible
on your system via the command
.IP
.B info \(aq(coreutils) base64 invocation\(aq
