.TH "chcon" 1 "GNU coreutils 8.28" "User Commands"
.SH NAME
chcon \- a GNU coreutils 8.28 program
.SH DESCRIPTION
.B OOOPS!
Due to the lack of perl on the build system, we were
unable to create a proper manual page for
.B chcon.
For concise option descriptions, run
.IP
.B env chcon --help
.PP
The full documentation for
.B chcon
is maintained as a Texinfo manual, which should be accessible
on your system via the command
.IP
.B info \(aq(coreutils) chcon invocation\(aq
