.TH "dircolors" 1 "GNU coreutils 8.28" "User Commands"
.SH NAME
dircolors \- a GNU coreutils 8.28 program
.SH DESCRIPTION
.B OOOPS!
Due to the lack of perl on the build system, we were
unable to create a proper manual page for
.B dircolors.
For concise option descriptions, run
.IP
.B env dircolors --help
.PP
The full documentation for
.B dircolors
is maintained as a Texinfo manual, which should be accessible
on your system via the command
.IP
.B info \(aq(coreutils) dircolors invocation\(aq
