.TH "seq" 1 "GNU coreutils 8.28" "User Commands"
.SH NAME
seq \- a GNU coreutils 8.28 program
.SH DESCRIPTION
.B OOOPS!
Due to the lack of perl on the build system, we were
unable to create a proper manual page for
.B seq.
For concise option descriptions, run
.IP
.B env seq --help
.PP
The full documentation for
.B seq
is maintained as a Texinfo manual, which should be accessible
on your system via the command
.IP
.B info \(aq(coreutils) seq invocation\(aq
