.TH "sha1sum" 1 "GNU coreutils 8.28" "User Commands"
.SH NAME
sha1sum \- a GNU coreutils 8.28 program
.SH DESCRIPTION
.B OOOPS!
Due to the lack of perl on the build system, we were
unable to create a proper manual page for
.B sha1sum.
For concise option descriptions, run
.IP
.B env sha1sum --help
.PP
The full documentation for
.B sha1sum
is maintained as a Texinfo manual, which should be accessible
on your system via the command
.IP
.B info \(aq(coreutils) sha1sum invocation\(aq
