.TH "whoami" 1 "GNU coreutils 8.28" "User Commands"
.SH NAME
whoami \- a GNU coreutils 8.28 program
.SH DESCRIPTION
.B OOOPS!
Due to the lack of perl on the build system, we were
unable to create a proper manual page for
.B whoami.
For concise option descriptions, run
.IP
.B env whoami --help
.PP
The full documentation for
.B whoami
is maintained as a Texinfo manual, which should be accessible
on your system via the command
.IP
.B info \(aq(coreutils) whoami invocation\(aq
